### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by amhsirak** [karishmas6/technet#11]
Looking for a cute simple favicon. You can discuss it here with me

**Comment by pccoder-2000** [comment]
Can i work on this issue? 
;)

**Comment by amhsirak** [comment]
@pccoder-2000 Sure, go ahead! 💯 Ask me if you have any questions

**Comment by captain-woof** [comment]
Can I work on this? Also, could you tell me what kind of favicons do you like?
