### ISSUE TITLE
Infinite loop of calling /api/profile/me after logging in

### ISSUE THREAD

**Issue by idiglove** [karishmas6/technet#13]
![Screen Shot 2021-10-04 at 10 56 21 AM](https://user-images.githubusercontent.com/29911508/135786610-03f170d4-683d-4dc1-8d21-a196b14aec9d.png)

**Comment by idiglove** [comment]
I will fix this on my next PR

**Comment by amhsirak** [comment]
@idiglove 👍 Coool

**Comment by idiglove** [comment]
Pls close this one too :)

**Comment by idiglove** [comment]
closed in #14
