### ISSUE TITLE
Enhance the UI

### ISSUE THREAD

**Issue by amhsirak** [karishmas6/technet#7]
Try to make the UI prettier! Feel free to use bootstrap or any other css framework if you want.

**Comment by idiglove** [comment]
Hi I would like to work on this, but Im having problems with starting up the server. Where should I put the mongo db credentials?

**Comment by amhsirak** [comment]
@idiglove You will have to make your MongoDB database :/ 
- You can register / sign in and proceed at https://www.mongodb.com/cloud/atlas/register
- Create your database
- Then in the `config` folder just create a file named `default.json` and add the *mongoURI*  provided.
That should fix it!

If you need help to get started with MongoDB Atlas, please ask!

**Comment by idiglove** [comment]
OK cool. Can you assign this issue to me? Thanks

**Comment by amhsirak** [comment]
@idiglove Yes! Keep me updated 💯

**Comment by idiglove** [comment]
![Screen Shot 2021-10-04 at 12 47 16 PM](https://user-images.githubusercontent.com/29911508/135795837-b5b7f5de-b510-4d64-ab35-3d991a509ff3.png)
My progress so far, using Material-UI

LMK if you're liking the direction of this

**Comment by amhsirak** [comment]
@idiglove Looks good to me! Keep going 🎉
