### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by amhsirak** [karishmas6/technet#8]
Make the README.md more interactive and cooler! Add images, emojies, etc. Go crazy!

**Comment by jatnnik** [comment]
Hey @karishmashuklaa, I'd like to work on this. Could you please assign me? :)

**Comment by amhsirak** [comment]
@wh1zk1d Go ahead 💯

**Comment by jatnnik** [comment]
Hey @karishmashuklaa, I created a PR #10
